version: '1'
services:
  web:
    container_name: TEAM_TOO_API
    hostname: team_too_api
    ports:
      - "3000:3000"		
    image: kainos-engacademy:team-too-ui
    environment:
      - API_URL=$API_URL
    depends_on:
      - backend
  backend:
    container_name: JDBC
    hostname: jdbc
    ports:
      - "8080:8080"
    image: kainos-engacademy:jdbc
    environment:
      - DB_HOST=$DB_HOST
      - DB_PASSWORD=$DB_PASSWORD
      - DB_USER=$DB_USER
      - DB_NAME=$DB_NAME
# Below code is required to use a local containerised db
#   depends_on:
#      - db
#  db:
#    image: mysql
#    container_name: MYSQLDB
#    hostname: mysqldb
#    ports:
#      - "3306:3306"
#    command: --default-authentication-plugin=mysql_native_password
#    environment:
#      MYSQL_ROOT_PASSWORD: $DB_PASSWORD